export type Size = "small" | "medium" | "large";

export interface Breed {
  id: string;
  name: string;
  emoji: string;
  tagline: string;
  description: string;
  size: Size;
  /** 1 = very low, 5 = very high */
  energy: number;
  grooming: number;
  trainability: number;
  goodWithKids: number;
  goodWithOtherPets: number;
  apartmentFriendly: number;
  independence: number;
  noviceFriendly: number;
  vocal: number;
  /** Suitability as a jogging/running companion, independent of general energy */
  runningPartner: number;
  heatTolerance: number;
  coldTolerance: number;
}

export const breeds: Breed[] = [
  {
    id: "labrador-retriever",
    name: "Labrador Retriever",
    emoji: "🦮",
    tagline: "The friendly, food-motivated all-rounder",
    description:
      "Easygoing, sociable, and eager to please. Labs thrive on daily exercise and love being part of family activities.",
    size: "large",
    energy: 5,
    grooming: 2,
    trainability: 5,
    goodWithKids: 5,
    goodWithOtherPets: 5,
    apartmentFriendly: 2,
    independence: 2,
    noviceFriendly: 5,
    vocal: 2,
    runningPartner: 5,
    heatTolerance: 3,
    coldTolerance: 4,
  },
  {
    id: "golden-retriever",
    name: "Golden Retriever",
    emoji: "🐕",
    tagline: "Gentle, affectionate, and endlessly patient",
    description:
      "One of the most family-friendly breeds around. Goldens are smart, trainable, and love having a job to do.",
    size: "large",
    energy: 4,
    grooming: 3,
    trainability: 5,
    goodWithKids: 5,
    goodWithOtherPets: 5,
    apartmentFriendly: 2,
    independence: 2,
    noviceFriendly: 5,
    vocal: 2,
    runningPartner: 4,
    heatTolerance: 3,
    coldTolerance: 4,
  },
  {
    id: "french-bulldog",
    name: "French Bulldog",
    emoji: "🐾",
    tagline: "A low-energy charmer built for city life",
    description:
      "Compact, comical, and content with short walks and a lot of couch time. Great for apartments.",
    size: "small",
    energy: 2,
    grooming: 1,
    trainability: 3,
    goodWithKids: 4,
    goodWithOtherPets: 3,
    apartmentFriendly: 5,
    independence: 2,
    noviceFriendly: 4,
    vocal: 2,
    runningPartner: 1,
    heatTolerance: 1,
    coldTolerance: 2,
  },
  {
    id: "standard-poodle",
    name: "Standard Poodle",
    emoji: "🐩",
    tagline: "Whip-smart and surprisingly athletic",
    description:
      "Highly intelligent and trainable, with a low-shedding coat that needs regular grooming to look its best.",
    size: "large",
    energy: 4,
    grooming: 5,
    trainability: 5,
    goodWithKids: 4,
    goodWithOtherPets: 4,
    apartmentFriendly: 3,
    independence: 2,
    noviceFriendly: 4,
    vocal: 2,
    runningPartner: 4,
    heatTolerance: 3,
    coldTolerance: 3,
  },
  {
    id: "chihuahua",
    name: "Chihuahua",
    emoji: "🐕‍🦺",
    tagline: "Tiny body, huge personality",
    description:
      "A big-city favorite that needs minimal exercise but plenty of affection. Can be vocal and wary of strangers.",
    size: "small",
    energy: 2,
    grooming: 1,
    trainability: 3,
    goodWithKids: 2,
    goodWithOtherPets: 2,
    apartmentFriendly: 5,
    independence: 2,
    noviceFriendly: 3,
    vocal: 5,
    runningPartner: 1,
    heatTolerance: 2,
    coldTolerance: 1,
  },
  {
    id: "beagle",
    name: "Beagle",
    emoji: "🐶",
    tagline: "A curious nose-led explorer",
    description:
      "Merry and social, beagles love company and outdoor sniffing adventures, though they can be vocal and stubborn.",
    size: "medium",
    energy: 4,
    grooming: 2,
    trainability: 3,
    goodWithKids: 5,
    goodWithOtherPets: 4,
    apartmentFriendly: 3,
    independence: 2,
    noviceFriendly: 3,
    vocal: 5,
    runningPartner: 3,
    heatTolerance: 3,
    coldTolerance: 3,
  },
  {
    id: "german-shepherd",
    name: "German Shepherd",
    emoji: "🐕‍🦺",
    tagline: "Loyal, confident, and hard-working",
    description:
      "Highly trainable and protective, German Shepherds need consistent exercise and mental stimulation to thrive.",
    size: "large",
    energy: 5,
    grooming: 3,
    trainability: 5,
    goodWithKids: 4,
    goodWithOtherPets: 3,
    apartmentFriendly: 2,
    independence: 3,
    noviceFriendly: 3,
    vocal: 3,
    runningPartner: 5,
    heatTolerance: 3,
    coldTolerance: 4,
  },
  {
    id: "border-collie",
    name: "Border Collie",
    emoji: "🐕",
    tagline: "The brainiest breed, built to work",
    description:
      "Extremely intelligent and energetic. Needs a job, a yard, and a lot of stimulation, or it will get creative on its own.",
    size: "medium",
    energy: 5,
    grooming: 3,
    trainability: 5,
    goodWithKids: 4,
    goodWithOtherPets: 3,
    apartmentFriendly: 1,
    independence: 2,
    noviceFriendly: 2,
    vocal: 3,
    runningPartner: 5,
    heatTolerance: 3,
    coldTolerance: 4,
  },
  {
    id: "bulldog",
    name: "English Bulldog",
    emoji: "🐾",
    tagline: "Low-key, dignified, and a little stubborn",
    description:
      "A relaxed companion that's happy with short strolls and long naps. Sensitive to heat and needs coat-fold care.",
    size: "medium",
    energy: 1,
    grooming: 2,
    trainability: 2,
    goodWithKids: 4,
    goodWithOtherPets: 3,
    apartmentFriendly: 5,
    independence: 3,
    noviceFriendly: 3,
    vocal: 1,
    runningPartner: 1,
    heatTolerance: 1,
    coldTolerance: 2,
  },
  {
    id: "cavalier-king-charles-spaniel",
    name: "Cavalier King Charles Spaniel",
    emoji: "🐕",
    tagline: "A velcro dog that loves everyone",
    description:
      "Sweet, affectionate, and adaptable to almost any home. Does best when it isn't left alone for long stretches.",
    size: "small",
    energy: 3,
    grooming: 3,
    trainability: 4,
    goodWithKids: 5,
    goodWithOtherPets: 5,
    apartmentFriendly: 5,
    independence: 1,
    noviceFriendly: 5,
    vocal: 2,
    runningPartner: 2,
    heatTolerance: 3,
    coldTolerance: 3,
  },
  {
    id: "dachshund",
    name: "Dachshund",
    emoji: "🌭",
    tagline: "A bold little hound with a big bark",
    description:
      "Playful and clever with a stubborn streak. Small enough for apartments but vocal and prone to alerting to everything.",
    size: "small",
    energy: 3,
    grooming: 2,
    trainability: 3,
    goodWithKids: 3,
    goodWithOtherPets: 3,
    apartmentFriendly: 4,
    independence: 3,
    noviceFriendly: 3,
    vocal: 5,
    runningPartner: 2,
    heatTolerance: 3,
    coldTolerance: 2,
  },
  {
    id: "shih-tzu",
    name: "Shih Tzu",
    emoji: "🐕",
    tagline: "A pint-sized lap dog with a flowing coat",
    description:
      "Affectionate and calm, happiest curled up with its people. Needs frequent grooming to keep its coat healthy.",
    size: "small",
    energy: 2,
    grooming: 5,
    trainability: 3,
    goodWithKids: 4,
    goodWithOtherPets: 4,
    apartmentFriendly: 5,
    independence: 2,
    noviceFriendly: 4,
    vocal: 2,
    runningPartner: 1,
    heatTolerance: 2,
    coldTolerance: 2,
  },
  {
    id: "australian-shepherd",
    name: "Australian Shepherd",
    emoji: "🐕‍🦺",
    tagline: "A tireless herder that needs a purpose",
    description:
      "Athletic, smart, and devoted, but happiest with acreage, a job to do, and an experienced, active owner.",
    size: "medium",
    energy: 5,
    grooming: 3,
    trainability: 5,
    goodWithKids: 4,
    goodWithOtherPets: 3,
    apartmentFriendly: 1,
    independence: 2,
    noviceFriendly: 2,
    vocal: 3,
    runningPartner: 5,
    heatTolerance: 3,
    coldTolerance: 4,
  },
  {
    id: "boxer",
    name: "Boxer",
    emoji: "🥊",
    tagline: "A goofy, loyal bundle of energy",
    description:
      "Playful and protective with a soft spot for kids. Boxers need regular exercise to stay out of mischief.",
    size: "large",
    energy: 5,
    grooming: 1,
    trainability: 3,
    goodWithKids: 5,
    goodWithOtherPets: 3,
    apartmentFriendly: 2,
    independence: 2,
    noviceFriendly: 3,
    vocal: 2,
    runningPartner: 4,
    heatTolerance: 2,
    coldTolerance: 3,
  },
  {
    id: "pug",
    name: "Pug",
    emoji: "🐶",
    tagline: "A comedic, cuddly companion",
    description:
      "Charming and low-exercise, pugs are content with short walks and lots of lounging. Sensitive to heat.",
    size: "small",
    energy: 2,
    grooming: 2,
    trainability: 3,
    goodWithKids: 5,
    goodWithOtherPets: 4,
    apartmentFriendly: 5,
    independence: 2,
    noviceFriendly: 5,
    vocal: 2,
    runningPartner: 1,
    heatTolerance: 1,
    coldTolerance: 2,
  },
  {
    id: "pembroke-welsh-corgi",
    name: "Pembroke Welsh Corgi",
    emoji: "🐕",
    tagline: "Short legs, big herding heart",
    description:
      "Smart, sturdy, and surprisingly energetic for their size. They bond closely and can be vocal watchdogs.",
    size: "small",
    energy: 4,
    grooming: 3,
    trainability: 4,
    goodWithKids: 4,
    goodWithOtherPets: 4,
    apartmentFriendly: 4,
    independence: 2,
    noviceFriendly: 4,
    vocal: 4,
    runningPartner: 2,
    heatTolerance: 3,
    coldTolerance: 3,
  },
  {
    id: "great-dane",
    name: "Great Dane",
    emoji: "🐕‍🦺",
    tagline: "A gentle giant with a surprisingly calm soul",
    description:
      "Despite their size, Danes are laid-back homebodies who just need space to stretch out and a loving family nearby.",
    size: "large",
    energy: 2,
    grooming: 1,
    trainability: 3,
    goodWithKids: 4,
    goodWithOtherPets: 3,
    apartmentFriendly: 2,
    independence: 2,
    noviceFriendly: 3,
    vocal: 2,
    runningPartner: 2,
    heatTolerance: 3,
    coldTolerance: 2,
  },
  {
    id: "siberian-husky",
    name: "Siberian Husky",
    emoji: "🐺",
    tagline: "A vocal, high-energy escape artist",
    description:
      "Striking and athletic, huskies need serious daily exercise and secure fencing. Not known for reliable recall.",
    size: "medium",
    energy: 5,
    grooming: 4,
    trainability: 2,
    goodWithKids: 4,
    goodWithOtherPets: 3,
    apartmentFriendly: 1,
    independence: 4,
    noviceFriendly: 1,
    vocal: 5,
    runningPartner: 5,
    heatTolerance: 1,
    coldTolerance: 5,
  },
  {
    id: "yorkshire-terrier",
    name: "Yorkshire Terrier",
    emoji: "🎀",
    tagline: "A tiny terrier with a big attitude",
    description:
      "Feisty and affectionate in equal measure. Small enough for any home, but needs regular coat care and confident handling.",
    size: "small",
    energy: 3,
    grooming: 4,
    trainability: 3,
    goodWithKids: 2,
    goodWithOtherPets: 2,
    apartmentFriendly: 5,
    independence: 2,
    noviceFriendly: 3,
    vocal: 4,
    runningPartner: 1,
    heatTolerance: 3,
    coldTolerance: 2,
  },
  {
    id: "basset-hound",
    name: "Basset Hound",
    emoji: "🐾",
    tagline: "A laid-back nose with short legs",
    description:
      "Mellow and easygoing with a famously good nose. Content with modest exercise but can be stubborn about training.",
    size: "medium",
    energy: 2,
    grooming: 2,
    trainability: 2,
    goodWithKids: 5,
    goodWithOtherPets: 4,
    apartmentFriendly: 4,
    independence: 3,
    noviceFriendly: 3,
    vocal: 4,
    runningPartner: 1,
    heatTolerance: 3,
    coldTolerance: 3,
  },
];
